# Generated by Django 5.2.8 on 2025-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=32)),
                ('body', models.TextField()),
                ('sender_id', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('FAILED', 'Failed'), ('THROTTLED', 'Throttled'), ('DELIVERED', 'Delivered'), ('BLOCKED_OPTOUT', 'Blocked Optout')], max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsOptIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('is_opted_in', models.BooleanField(default=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
